### ISSUE TITLE
Kleuren

### ISSUE THREAD

**Issue by KoopReynders** [cmda-minor-web/web-app-from-scratch-1920#1]
https://github.com/cmda-minor-web/web-app-from-scratch-1920/blob/07b9a0e43fd8524ddca05c7502952f7ff8a6e0da/docs/css/styles.css#L3

Techy vakken:Blauwiug
En designy vakken: Geelig
Projecten: Groenig
Dan krijgen we een mooi koud/warmcontrast.

<img width="179" alt="image" src="https://user-images.githubusercontent.com/1391509/73576309-75b95300-447a-11ea-9270-84a2485669a0.png">

Bijvoorbeeld:
#00B0FC
#F4E408
#00CD84

<img width="208" alt="image" src="https://user-images.githubusercontent.com/1391509/73576433-bca74880-447a-11ea-9bf5-61ff04fa5576.png">

**Comment by KoopReynders** [comment]
@joostf

**Comment by joostf** [comment]
Nice, ik heb het overal waar het nog niet doorgevoerd was doorgevoerd
